# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: poetry-black
        name: Format python code by black
        entry: poetry
        args:
        -   run
        -   black
        -   .
        language: system
        pass_filenames: false
    -   id: poetry-isort
        name: Format python code by isort
        entry: poetry
        args:
        -   run
        -   isort
        -   .
        language: system
        pass_filenames: false
    -   id: poetry-pflake8
        name: Check python code by pflake8
        entry: poetry
        args:
        -   run
        -   pflake8
        language: system
        pass_filenames: false
    -   id: poetry-sphinx-apidoc
        name: Make .rst from .py sources
        entry: poetry
        args:
        -   run
        -   python
        -   .pre-commit/sphinx_apidoc.py
        -   --module=modelicalang/
        -   --output=document/apis/
        language: system
        pass_filenames: false
        files: ^(\.pre\-commit/sphinx_apidoc\.py$|modelicalang/)
