[tool.poetry]
name = "ModelicaLanguage"
version = "0.0.0a6"
description = ""
authors = ["ijknabla <ijknabla@gmail.com>"]
license = "MIT"
classifiers = [
        "Development Status :: 3 - Alpha",
        "Programming Language :: Python :: 3 :: Only",
]
packages = [
    { include = "modelica_language"},
]

[tool.poetry.dependencies]
python = "^3.6"
Arpeggio = ">=1.6"

[tool.poetry.dev-dependencies]
pyproject-flake8 = "^0.0.1-alpha.2"
mypy = "^0.910"
pytest = "^6.2.5"
black = ">=20.8.b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
